sonar.projectKey=saldu-web
sonar.projectName=saldu-web

# Source & Test Code Separation
sonar.sources=src
sonar.tests=tests
sonar.test.inclusions=tests/**/*.test.ts,tests/**/*.test.tsx,tests/**/*.ts,tests/**/*.tsx

# Coverage Exclusions (Do not count test files or type declarations as uncovered source code)
sonar.coverage.exclusions=tests/**,**/*.test.ts,**/*.test.tsx,**/*.d.ts,src/types/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
